services:
  backend:
    image: maven:3.9.9-eclipse-temurin-17
    working_dir: /app
    command: mvn -q spring-boot:run
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - maven-repo:/root/.m2

  frontend:
    image: node:22-alpine
    working_dir: /usr/src/app
    command: sh -c "npm ci && npm start"
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app

volumes:
  maven-repo: